ko_fi: tunnckoCore# Replace with a single Ko-fi username
issuehunt: tunnckoCore # Replace with a single IssueHunt username
custom: 
  - https://gumroad.com/l/tunnckoCoreRecurringDonation
  - https://gumroad.com/l/tunnckoCorePatronLicense
